### ISSUE TITLE
FAQ: Getting Involved

### ISSUE THREAD

**Issue by bretbrownjr** [beman-project/beman#32]
When someone hears about the Beman Project and wants to get involved, there should be a quick step-by-step to discover could be done, pick up some of that work, and get support when completing that work.

This issue will be done when there is an FAQ entry for getting involved in the Beman Project. If the content becomes too long for an entry for an FAQ, creating a standalone document and linking to it from the FAQ is acceptable.

For reference, [here is a link to the existing FAQ](https://github.com/beman-project/beman#faq) for reference.

**Mentor**: @bretbrownjr is available to answer questions and review pull requests for this issue.

**Comment by bretbrownjr** [comment]
As a timeliness goal, it makes sense to have this fully fleshed out before @camio gives his talk at CppCon in mid-September.

For inspiration, the Carbon Language has a [Join Us](https://github.com/carbon-language/carbon-lang?tab=readme-ov-file#join-us) document to consider.

**Comment by linusboehm** [comment]
1. what is the difference between the FAQ section in the README.md and the `beman/docs/FAQ.md`? Should we move the FAQ section of the README.md into the FAQ.md?
2. The [Discourse for new joiners](https://discourse.boost.org/t/welcome-to-the-beman-project-discourse-start-here/40) link in the README.md seems to be dead

**Comment by camio** [comment]
> The [Discourse for new joiners](https://discourse.boost.org/t/welcome-to-the-beman-project-discourse-start-here/40) link in the README.md seems to be dead

That link predates the move to discourse.bemanproject.org and probably just needs to be updated.
